import { expect, test } from '@playwright/test'

test('operator completes personnel, incident, shift and credential workflows', async ({ page }) => {
  test.setTimeout(120_000)
  const name = `QA synthetic ${Date.now()}`
  await page.goto('/')
  await page.getByRole('button', { name: 'Sign in to command' }).click()
  await page.getByLabel(/Username|Email/).fill('duty.officer')
  await page.getByLabel('Password', { exact: true }).fill('aegis-local-only')
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: /Fairfax County readiness board/i })).toBeVisible({ timeout: 20_000 })

  // Navigation stays within the authenticated app; tokens are deliberately memory-only.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Personnel/ }).click()
  await page.getByRole('button', { name: 'Add personnel', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Full name', { exact: true }).fill(name)
  await dialog.getByLabel('Operational role').fill('QA Firefighter')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel(/^Credentials/).fill('FF2, HAZMAT-OPS, DRIVER, EMT, PARAMEDIC, ACLS, AERIAL, TECH-RESCUE, ICS-300, SAFETY, HAZMAT-TECH')
  await dialog.getByLabel('Verified credential expiration').fill('2030-12-31')
  await dialog.getByRole('button', { name: 'Add personnel', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Incidents/ }).click()
  await page.getByRole('button', { name: /open incident/i }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Incident title').fill(name)
  await dialog.getByLabel('Display location').fill('12000 Fair Oaks Mall, Fairfax, VA')
  await dialog.getByRole('button', { name: 'Open incident', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.getByLabel('Search incidents').fill(name)
  const incident = page.locator('.it-register tbody tr').filter({ hasText: name })
  await expect(incident).toBeVisible()
  await incident.getByRole('button', { name: /^Select I-.*EMS/ }).click()
  await expect(page.locator('.it-f-location input')).toHaveValue('12000 Fair Oaks Mall, Fairfax, VA')
  // Status change is persisted and appears as a recorded lifecycle stage.
  await page.locator('.it-f-status select').selectOption('ON_SCENE')
  await page.getByRole('button', { name: 'SAVE CHANGES' }).click()
  await expect(incident.locator('.it-stamp')).toHaveText('ON SCENE')
  await expect(page.locator('.it-row-group.is-selected .it-seg[aria-label*="ON SCENE"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'ADD NOTE' }).click()
  await page.getByRole('dialog').locator('textarea').fill('QA note recorded.')
  await page.getByRole('dialog').getByRole('button', { name: 'Add note' }).click()
  await expect(page.locator('.it-f-notes textarea')).toHaveValue(/QA note recorded\./)
  await page.getByRole('button', { name: 'ASSIGN UNITS' }).click()
  dialog = page.getByRole('dialog')
  const assignedUnit = dialog.locator('.theater-assignment-list input[type="checkbox"]').first()
  await assignedUnit.check()
  await dialog.getByRole('button', { name: 'Save unit assignments' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'ASSIGN UNITS' }).click()
  await expect(page.getByRole('dialog').locator('.theater-assignment-list input[type="checkbox"]').first()).toBeChecked()
  await page.getByRole('dialog').getByRole('button', { name: 'Close dialog' }).click()
  page.once('dialog', async (confirmation) => { await confirmation.accept() })
  await page.getByRole('button', { name: 'RESOLVE INCIDENT' }).click()
  await expect(incident.locator('.it-stamp')).toHaveText('CLOSED')
  // Recorded lifecycle: the timeline shows the assignment window closed at resolution.
  await page.getByLabel('Unit activity').check()
  await expect(page.locator('.it-row-group').filter({ has: page.locator('.it-row-label', { hasText: /^I-/ }) }).first()).toBeVisible()

  // Unit service state: confirmed maintenance and return are recorded and reconstructed on the timeline.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Units/ }).click()
  await page.locator('.sb-search input').fill('T401')
  await page.getByRole('button', { name: /^T401, Truck/ }).click()
  await expect(page).toHaveURL(/unit=unit-truck-01/)
  await expect(page.locator('#sb-dossier-heading')).toHaveText('TRUCK 401', { timeout: 20_000 })
  page.once('dialog', async (confirmation) => { await confirmation.accept() })
  await page.locator('.sb-actions').getByRole('button', { name: 'Out of service' }).click()
  await page.getByRole('menuitem', { name: /Maintenance/ }).click()
  await expect(page.locator('.sb-service')).toContainText('MAINTENANCE')
  await expect(page.locator('.sb-row.is-selected .sb-seg.tone-maintenance')).toHaveCount(1)
  page.once('dialog', async (confirmation) => { await confirmation.accept() })
  await page.getByRole('button', { name: 'Return unit' }).click()
  await expect(page.locator('.sb-service')).toContainText('IN SERVICE')

  await page.getByRole('button', { name: /Search unit, station, incident, location/ }).click()
  await page.getByLabel('Search workspaces and actions').fill('Scheduling')
  await page.getByRole('button', { name: /Scheduling/ }).click()
  await page.getByRole('button', { name: 'Create shift', exact: true }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel('Location override').fill(name)
  const times = await page.evaluate(() => [-5, 60].map(minutes => {
    const date = new Date(Date.now() + minutes * 60_000)
    return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
  }))
  await dialog.getByLabel('Start', { exact: true }).fill(times[1])
  await dialog.getByLabel('End', { exact: true }).fill(times[0])
  await dialog.getByLabel('Required headcount').fill('1')
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('end_time must be after start_time')
  await dialog.getByLabel('Start', { exact: true }).fill(times[0])
  await dialog.getByLabel('End', { exact: true }).fill(times[1])
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add to roster', exact: true }).click()
  dialog = page.getByRole('dialog')
  const personId = await dialog.locator('option').filter({ hasText: name }).getAttribute('value')
  await dialog.getByLabel('Personnel', { exact: true }).selectOption(personId!)
  await dialog.getByRole('button', { name: 'Add to roster', exact: true }).click()
  await expect(dialog).toBeHidden()
  const roster = page.locator('.roster-row').filter({ hasText: name })
  await roster.getByRole('button', { name: 'Clock in' }).click()
  await expect(roster.getByRole('button', { name: 'Clock out' })).toBeVisible()
  await roster.getByRole('button', { name: 'Clock out' }).click()
  await expect(roster.getByRole('button', { name: 'Clock in' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel shift', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Add to roster', exact: true })).toBeDisabled()

  await page.getByRole('button', { name: /Search unit, station, incident, location/ }).click()
  await page.getByLabel('Search workspaces and actions').fill('Credentials')
  await page.getByRole('button', { name: /Credentials/ }).click()
  await page.getByRole('button', { name: 'Add credential', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Credential name').fill(name)
  await dialog.getByLabel('Category', { exact: true }).fill('Synthetic QA')
  await dialog.getByRole('button', { name: 'Save credential' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('tab', { name: /Credential library/ }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete unused' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.credential-list-row').filter({ hasText: name })).toHaveCount(0)

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Personnel/ }).click()
  await page.getByPlaceholder('Search name, role, or rank').fill(name)
  await page.getByRole('button', { name: 'Archive record' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.person-list-row')).toHaveCount(0)
})
