import { expect, test } from '@playwright/test'

test('operator completes personnel, incident, shift and credential workflows', async ({ page }) => {
  test.setTimeout(120_000)
  const name = `QA synthetic ${Date.now()}`
  await page.goto('/')
  await page.getByRole('button', { name: 'Sign in to command' }).click()
  await page.getByLabel(/Username|Email/).fill('duty.officer')
  await page.getByLabel('Password', { exact: true }).fill('aegis-local-only')
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page.locator('h1')).toContainText('Every resource.', { timeout: 20_000 })

  // Navigation stays within the authenticated app; tokens are deliberately memory-only.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: 'Workforce' }).click()
  await page.getByRole('button', { name: 'Add personnel', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Full name', { exact: true }).fill(name)
  await dialog.getByLabel('Operational role').fill('QA Firefighter')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel(/^Credentials/).fill('FF2, HAZMAT-OPS, DRIVER, EMT, PARAMEDIC, ACLS, AERIAL, TECH-RESCUE, ICS-300, SAFETY, HAZMAT-TECH')
  await dialog.getByLabel('Verified credential expiration').fill('2030-12-31')
  await dialog.getByRole('button', { name: 'Add personnel', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: 'Operations' }).click()
  await page.getByRole('button', { name: 'Open incident', exact: true }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Incident title').fill(name)
  await dialog.getByRole('button', { name: 'Open incident', exact: true }).click()
  await expect(dialog).toBeHidden()
  const incident = page.locator('.incident-card').filter({ has: page.getByRole('heading', { name, exact: true }) })
  await expect(incident).toBeVisible()
  await incident.getByRole('button', { name: 'Close incident' }).click()
  await expect(incident).toHaveCount(0)

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: 'Scheduling' }).click()
  await page.getByRole('button', { name: 'Create shift', exact: true }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel('Location override').fill(name)
  const times = await page.evaluate(() => [-5, 60].map(minutes => {
    const date = new Date(Date.now() + minutes * 60_000)
    return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
  }))
  await dialog.getByLabel('Start', { exact: true }).fill(times[1])
  await dialog.getByLabel('End', { exact: true }).fill(times[0])
  await dialog.getByLabel('Required headcount').fill('1')
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('end_time must be after start_time')
  await dialog.getByLabel('Start', { exact: true }).fill(times[0])
  await dialog.getByLabel('End', { exact: true }).fill(times[1])
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add to roster', exact: true }).click()
  dialog = page.getByRole('dialog')
  const personId = await dialog.locator('option').filter({ hasText: name }).getAttribute('value')
  await dialog.getByLabel('Personnel', { exact: true }).selectOption(personId!)
  await dialog.getByRole('button', { name: 'Add to roster', exact: true }).click()
  await expect(dialog).toBeHidden()
  const roster = page.locator('.roster-row').filter({ hasText: name })
  await roster.getByRole('button', { name: 'Clock in' }).click()
  await expect(roster.getByRole('button', { name: 'Clock out' })).toBeVisible()
  await roster.getByRole('button', { name: 'Clock out' }).click()
  await expect(roster.getByRole('button', { name: 'Clock in' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel shift', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Add to roster', exact: true })).toBeDisabled()

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: 'Credentials' }).click()
  await page.getByRole('button', { name: 'Add credential', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Credential name').fill(name)
  await dialog.getByLabel('Category', { exact: true }).fill('Synthetic QA')
  await dialog.getByRole('button', { name: 'Save credential' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('tab', { name: /Credential library/ }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete unused' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.credential-list-row').filter({ hasText: name })).toHaveCount(0)

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: 'Workforce' }).click()
  await page.getByPlaceholder('Search name, role, or rank').fill(name)
  await page.getByRole('button', { name: 'Archive record' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.person-list-row')).toHaveCount(0)
})
