import { expect, test } from '@playwright/test'

test('operator completes personnel, incident, shift and credential workflows', async ({ page }) => {
  test.setTimeout(120_000)
  const name = `QA synthetic ${Date.now()}`
  await page.goto('/')
  await page.getByRole('button', { name: 'Sign in to command' }).click()
  await page.getByLabel(/Username|Email/).fill('duty.officer')
  await page.getByLabel('Password', { exact: true }).fill('aegis-local-only')
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: /Fairfax County readiness board/i })).toBeVisible({ timeout: 20_000 })

  // Navigation stays within the authenticated app; tokens are deliberately memory-only.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Personnel/ }).click()
  await page.getByRole('button', { name: 'Add personnel', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Full name', { exact: true }).fill(name)
  await dialog.getByLabel('Operational role').fill('QA Firefighter')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel(/^Credentials/).fill('FF2, HAZMAT-OPS, DRIVER, EMT, PARAMEDIC, ACLS, AERIAL, TECH-RESCUE, ICS-300, SAFETY, HAZMAT-TECH')
  await dialog.getByLabel('Verified credential expiration').fill('2030-12-31')
  await dialog.getByRole('button', { name: 'Add personnel', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Incidents/ }).click()
  await page.getByRole('button', { name: /open incident/i }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Incident title').fill(name)
  await dialog.getByLabel('Display location').fill('12000 Fair Oaks Mall, Fairfax, VA')
  await dialog.getByRole('button', { name: 'Open incident', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.getByLabel('Search incidents').fill(name)
  const incident = page.locator('[data-ui="incident-register"] tbody tr').filter({ hasText: name })
  await expect(incident).toBeVisible()
  await incident.getByRole('button', { name: /^Select I-.*EMS/ }).click()
  await expect(page.locator('[data-ui="incident-location"]')).toHaveValue('12000 Fair Oaks Mall, Fairfax, VA')
  // Status change is persisted and appears as a recorded lifecycle stage.
  await page.locator('[data-ui="incident-status-select"]').selectOption('ON_SCENE')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(incident.locator('[data-ui="incident-status"]')).toHaveText('On scene')
  const incidentPane = (pane: string) => page.getByRole('tablist', { name: 'Incident views' }).getByRole('tab', { name: pane, exact: true })
  await incidentPane('Timeline').click()
  await expect(page.locator('[data-ui="timeline-group"][data-selected] [data-ui="timeline-stage"][aria-label*="ON SCENE"]')).toHaveCount(1)
  await incidentPane('Register').click()
  await page.getByRole('button', { name: 'Add note' }).click()
  await page.getByRole('dialog').locator('textarea').fill('QA note recorded.')
  await page.getByRole('dialog').getByRole('button', { name: 'Add note' }).click()
  await expect(page.locator('[data-ui="incident-notes"]')).toHaveValue(/QA note recorded\./)
  await page.getByRole('button', { name: 'Assign units' }).click()
  dialog = page.getByRole('dialog')
  const assignedUnit = dialog.locator('[data-ui="assignment-list"] input[type="checkbox"]').first()
  await assignedUnit.check()
  await dialog.getByRole('button', { name: 'Save unit assignments' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Assign units' }).click()
  await expect(page.getByRole('dialog').locator('[data-ui="assignment-list"] input[type="checkbox"]').first()).toBeChecked()
  await page.getByRole('dialog').getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Resolve incident' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Resolve incident' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(incident.locator('[data-ui="incident-status"]')).toHaveText('Closed')
  await incidentPane('Timeline').click()
  // Recorded lifecycle: the timeline shows the assignment window closed at resolution.
  await page.getByLabel('Unit activity').check()
  await expect(page.locator('[data-ui="timeline-group"]').first()).toBeVisible()

  // Unit service state: confirmed maintenance and return are recorded and reconstructed on the timeline.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Units/ }).click()
  await page.locator('[data-ui="unit-search"]').fill('T401')
  await page.getByRole('button', { name: /^T401, Truck/ }).click()
  await expect(page).toHaveURL(/unit=unit-truck-01/)
  await expect(page.locator('#unit-record-heading')).toHaveText('Truck 401', { timeout: 20_000 })
  await page.locator('[data-ui="unit-actions"]').getByRole('button', { name: 'Out of service' }).click()
  await page.getByRole('menuitem', { name: /Maintenance/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Place in maintenance' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('[data-ui="unit-service"]')).toContainText('Maintenance')
  await page.getByRole('button', { name: 'View history' }).click()
  await expect(page.locator('[data-ui="unit-history-row"][data-selected] [data-ui="unit-bar"][data-tone="maintenance"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Return unit' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Return to service' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('[data-ui="unit-service"]')).toContainText('In service')

  // Scenario results are projections; recorded apparatus readiness does not change.
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Plans & Hazards/ }).click()
  await page.getByLabel('Scenario apparatus').selectOption('unit-engine-01')
  const baseline = await page.locator('[data-ui="comparison"] strong').first().textContent()
  await page.getByRole('button', { name: 'Calculate scenario', exact: true }).click()
  await expect(page.locator('[data-ui="comparison"] strong').nth(1)).not.toHaveText('—')
  await expect(page.locator('[data-ui="comparison"] strong').first()).toHaveText(baseline!)
  await expect(page.locator('[data-ui="recovery"] li').first()).toBeVisible()
  await page.getByRole('button', { name: 'Reset scenario', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Awaiting calculation' })).toBeVisible()
  await expect(page.locator('[data-ui="comparison"] strong').first()).toHaveText(baseline!)

  await page.getByRole('button', { name: /Search unit, station, incident, location/ }).click()
  await page.getByLabel('Search workspaces and actions').fill('Scheduling')
  await page.getByRole('button', { name: /Scheduling/ }).click()
  await page.getByRole('button', { name: 'Create shift', exact: true }).first().click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Station', { exact: true }).selectOption('fs-01')
  await dialog.getByLabel('Location override').fill(name)
  const times = await page.evaluate(() => [-5, 60].map(minutes => {
    const date = new Date(Date.now() + minutes * 60_000)
    return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
  }))
  await dialog.getByLabel('Start', { exact: true }).fill(times[1])
  await dialog.getByLabel('End', { exact: true }).fill(times[0])
  await dialog.getByLabel('Required headcount').fill('1')
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('end_time must be after start_time')
  await dialog.getByLabel('Start', { exact: true }).fill(times[0])
  await dialog.getByLabel('End', { exact: true }).fill(times[1])
  await dialog.getByRole('button', { name: 'Create shift', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add to roster', exact: true }).click()
  dialog = page.getByRole('dialog')
  const personId = await dialog.locator('option').filter({ hasText: name }).getAttribute('value')
  await dialog.getByLabel('Personnel', { exact: true }).selectOption(personId!)
  await dialog.getByRole('button', { name: 'Add to roster', exact: true }).click()
  await expect(dialog).toBeHidden()
  const roster = page.locator('[data-ui="roster-row"]').filter({ hasText: name })
  await roster.getByRole('button', { name: 'Clock in' }).click()
  await expect(roster.getByRole('button', { name: 'Clock out' })).toBeVisible()
  await roster.getByRole('button', { name: 'Clock out' }).click()
  await expect(roster.getByRole('button', { name: 'Clock in' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel shift', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Add to roster', exact: true })).toBeDisabled()

  await page.getByRole('button', { name: /Search unit, station, incident, location/ }).click()
  await page.getByLabel('Search workspaces and actions').fill('Credentials')
  await page.getByRole('button', { name: /Credentials/ }).click()
  await page.getByRole('button', { name: 'Add credential', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Credential name').fill(name)
  await dialog.getByLabel('Category', { exact: true }).fill('Synthetic QA')
  await dialog.getByRole('button', { name: 'Save credential' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('tab', { name: /Credential library/ }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete unused' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('[data-ui="credential-row"]').filter({ hasText: name })).toHaveCount(0)

  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('link', { name: /Personnel/ }).click()
  await page.getByPlaceholder('Search name, role, or rank').fill(name)
  await page.getByRole('button', { name: 'Archive record' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm action' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('[data-ui="person-row"]')).toHaveCount(0)
})
