'use client'

import { useState } from 'react'
import Link from 'next/link'
import type { SimulationResult, Unit, UnitReadiness } from '@/lib/schemas'
import { Button, WriteButton, EmptyState, PageHeader, SectionHeader, StatusBadge } from './ui'
import { ComparisonInstrument } from './OperatingSurfaces'
import { formatDate } from '@/lib/utils'

export default function ContingencyWorkbench({ units, definitions, selected, result, busy, onSelect, onRun, onReset }: {
  units: UnitReadiness[]; definitions: Unit[]; selected?: UnitReadiness; result?: SimulationResult; busy: boolean
  onSelect: (id: string) => void; onRun: (unitId: string, personnelId?: string) => void; onReset: () => void
}) {
  const [scenario, setScenario] = useState('offline')
  const [personId, setPersonId] = useState('')
  const definition = definitions.find(unit => unit.unit_id === selected?.unit_id)
  const person = selected?.assigned_personnel.find(item => item.personnel_id === personId) || selected?.assigned_personnel[0]
  const after = result?.degraded_readiness.find(unit => unit.unit_id === selected?.unit_id)
  return <>
    <PageHeader eyebrow="Hypothetical staffing analysis" title="Plans & Hazards" description="Test an apparatus outage or crew callout against recorded readiness. This workbench makes no live changes and does not predict travel time or response coverage." />
    <section className="civic-plate"><SectionHeader title="Contingency control register" description="Choose the asset and disruption before calculating its qualification and staffing impact" /><div className="contingency-controls"><label>Apparatus<select disabled={busy} aria-label="Scenario apparatus" value={selected?.unit_id || ''} onChange={event => { onSelect(event.target.value); setPersonId('') }}>{units.map(unit => <option key={unit.unit_id} value={unit.unit_id}>{unit.unit_name} · {unit.readiness_score}%</option>)}</select></label><label>Disruption<select disabled={busy} aria-label="Scenario disruption" value={scenario} onChange={event => { setScenario(event.target.value); onReset() }}><option value="offline">Apparatus out of service</option><option value="callout">One crew member unavailable</option></select></label>{scenario === 'callout' && <label>Crew member<select disabled={busy} aria-label="Scenario crew member" value={person?.personnel_id || ''} onChange={event => { setPersonId(event.target.value); onReset() }}><option value="" disabled>Select recorded crew</option>{selected?.assigned_personnel.map(item => <option key={item.personnel_id} value={item.personnel_id}>{item.name}</option>)}</select></label>}<WriteButton variant="primary" busy={busy} disabled={!selected || (scenario === 'callout' && !person)} onClick={() => selected && onRun(selected.unit_id, scenario === 'callout' ? person?.personnel_id : undefined)}>Calculate scenario</WriteButton><Button disabled={busy} onClick={() => { onReset(); setScenario('offline'); setPersonId('') }}>Reset scenario</Button></div></section>
    <div className="contingency-layout">
      <section className="civic-plate"><SectionHeader title="Asset & crew dependency register" description={selected ? `${selected.unit_name} · ${selected.staff_present}/${selected.staff_required} staffing` : 'Select recorded apparatus'} />{selected ? <><dl className="civic-facts"><div><dt>Required qualifications</dt><dd>{definition?.required_certifications.join(' / ') || 'No specific qualifications recorded'}</dd></div><div><dt>Baseline issues</dt><dd>{selected.issues.join('; ') || 'No issues returned'}</dd></div><div><dt>Recorded snapshot</dt><dd>{formatDate(selected.timestamp, 'MMM d · HH:mm')}</dd></div></dl><div className="contingency-crew">{selected.assigned_personnel.map(item => <button type="button" disabled={busy} className="evidence-link w-full text-left" key={item.personnel_id} aria-pressed={scenario === 'callout' && item.personnel_id === person?.personnel_id} onClick={() => { setScenario('callout'); setPersonId(item.personnel_id); onReset() }}><span><strong>{item.name}</strong><small className="block">{item.role} · {item.certifications.join(' / ')}</small></span><StatusBadge tone={scenario === 'callout' && item.personnel_id === person?.personnel_id ? 'warning' : 'info'}>{scenario === 'callout' && item.personnel_id === person?.personnel_id ? 'Scenario callout' : 'Recorded crew'}</StatusBadge></button>)}</div>{!selected.assigned_personnel.length && <p className="civic-empty">No assigned crew. Use the apparatus outage scenario.</p>}<div className="civic-links"><Link href={`/readiness?view=units&unit=${encodeURIComponent(selected.unit_id)}`}>Inspect live apparatus</Link><Link href="/weather">Public hazard register</Link></div></> : <EmptyState title="No apparatus in scope" description="Choose another station scope to run a scenario." />}</section>
      <section className="civic-plate"><SectionHeader title="Projected readiness & recovery worksheet" description={result ? `Hypothetical result · ${formatDate(result.timestamp, 'HH:mm')}` : 'Live operational records remain unchanged'} />{selected && <ComparisonInstrument before={result?.original_readiness.find(unit => unit.unit_id === selected.unit_id)?.readiness_score ?? selected.readiness_score} after={after?.readiness_score} />}{result ? <><dl className="civic-facts"><div><dt>Impacted units</dt><dd>{result.impacted_units.map(id => units.find(unit => unit.unit_id === id)?.unit_name || id).join(', ') || 'None returned'}</dd></div><div><dt>Projected issues</dt><dd>{after?.issues.join('; ') || 'No issues returned'}</dd></div></dl><ol className="recovery-worksheet">{result.recovery_actions.map(action => <li key={action}>{action}</li>)}</ol>{!result.recovery_actions.length && <p className="civic-empty">No recovery actions were returned for this scenario.</p>}</> : <EmptyState title="Awaiting calculation" description="Select a disruption and calculate to inspect its projected consequences and recovery actions." />}<p className="civic-provenance">Hypothetical planning only. Staffing and qualification dependencies come from synthetic operational records; no emergency plan is issued.</p></section>
    </div>
  </>
}
