'use client'

import { useState } from 'react'
import type { AuditEvent, FairfaxWeather } from '@/lib/schemas'
import { SectionHeader, StatusBadge } from './ui'
import { formatDate } from '@/lib/utils'

export function ForecastInstrument({ data, selectedIndex, onSelect }: { data: FairfaxWeather; selectedIndex: number; onSelect: (index: number) => void }) {
  const periods = data.forecast_periods
  const selected = periods[selectedIndex] || periods[0]
  const values = periods.map(period => period.temperature).filter((value): value is number => typeof value === 'number')
  const minimum = Math.min(...values) - 5, maximum = Math.max(...values) + 5
  const x = (index: number) => 45 + index / Math.max(1, periods.length - 1) * 810
  const y = (temperature: number) => 165 - (temperature - minimum) / Math.max(1, maximum - minimum) * 130
  const directions = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']
  const direction = directions.indexOf((selected?.wind_direction || '').toUpperCase())
  return <section className="civic-plate"><SectionHeader title="Forecast period instrument" description="Select a forecast period for its temperature, wind, and detailed outlook · not observed weather" /><div className="forecast-console"><div className="forecast-plot">{values.length ? <svg viewBox="0 0 900 200" role="img" aria-label={`Forecast temperatures by NWS period, from ${Math.min(...values)} to ${Math.max(...values)} degrees`}>
    {[0, 1, 2, 3, 4].map(tick => { const value = minimum + (maximum - minimum) * tick / 4; return <g key={tick}><line x1="45" x2="855" y1={y(value)} y2={y(value)} stroke="#365564" strokeWidth="1" /><text x="6" y={y(value) + 4}>{Math.round(value)}°</text></g> })}
    {periods.map((period, index) => period.temperature != null && <g key={index}><line x1={x(index)} x2={x(index)} y1="22" y2="166" stroke={index === selectedIndex ? '#d8c38f' : '#294755'} strokeDasharray={index === selectedIndex ? '4 4' : undefined} /><circle cx={x(index)} cy={y(period.temperature)} r={index === selectedIndex ? 6 : 3} fill={index === selectedIndex ? '#efe8d7' : '#91b49f'} /><text x={x(index)} y="188" textAnchor="middle">{index + 1}</text></g>)}
    {periods.slice(1).map((period, index) => period.temperature != null && periods[index].temperature != null && <line key={index} x1={x(index)} y1={y(periods[index].temperature!)} x2={x(index + 1)} y2={y(period.temperature)} stroke="#91b49f" strokeWidth="2" />)}
  </svg> : <p className="civic-empty" style={{ color: '#c4d2d3' }}>Temperature readings unavailable. Use the official source or refresh the register.</p>}<div className="forecast-periods" aria-label="Forecast periods">{periods.map((period, index) => <button type="button" key={index} aria-pressed={index === selectedIndex} onClick={() => onSelect(index)}><span>{index + 1}. {period.name || 'Period'}</span><strong>{period.temperature == null ? '—' : `${period.temperature}°${period.temperature_unit || 'F'}`}</strong><small>{period.short_forecast || 'Not reported'}</small></button>)}</div><p className="civic-provenance" style={{ color: '#c4d2d3', paddingLeft: 0 }}>NWS period forecast · {data.stale ? 'stale cached report' : data.status === 'unavailable' ? 'unavailable' : 'current report'} · no interpolation between missing readings</p></div><div className="forecast-selection" aria-live="polite"><h3>{selected?.name || 'No forecast periods'}</h3><p>{selected?.detailed_forecast || 'A detailed forecast was not returned.'}</p><div className="wind-instrument"><svg viewBox="0 0 100 100" role="img" aria-label={direction < 0 ? 'Wind direction not reported' : `Wind from ${selected?.wind_direction}`}><circle cx="50" cy="50" r="34" fill="none" stroke="#70858f" /><line x1="50" y1="20" x2="50" y2="80" stroke="#9da7a6" /><line x1="20" y1="50" x2="80" y2="50" stroke="#9da7a6" /><text x="50" y="12" textAnchor="middle" fontSize="10" fill="#244a63">N</text>{direction >= 0 && <path d="M50 24 L43 44 L50 40 L57 44 Z M50 40 L50 74" transform={`rotate(${direction * 22.5} 50 50)`} fill="#244a63" stroke="#244a63" strokeWidth="2" />}</svg><div><span>Wind from {selected?.wind_direction || 'unreported'}</span><strong>{selected?.wind_speed || '—'}</strong></div></div><dl className="civic-facts"><div><dt>Period starts</dt><dd>{formatDate(selected?.start_time, 'MMM d · HH:mm')}</dd></div><div><dt>Precipitation</dt><dd>{selected?.probability_of_precipitation == null ? 'Not reported' : `${selected.probability_of_precipitation}% probability`}</dd></div></dl></div></div></section>
}

export function AssuranceInstrument({ identityReady, operationsReady, checking, snapshotTime, auditReady, onRefresh }: { identityReady: boolean; operationsReady: boolean; checking: boolean; snapshotTime?: string; auditReady: boolean; onRefresh: () => void }) {
  const [selected, setSelected] = useState('operations')
  const checks = [
    { id: 'identity', title: 'Session identity', subtitle: 'Effective access response', ready: identityReady, detail: 'The application access response reports the current display identity and effective permissions. Server-side authorization remains authoritative.' },
    { id: 'operations', title: 'Operating picture', subtitle: 'Tenant-scoped snapshot', ready: operationsReady, detail: `A successful response verifies this browser can retrieve the operating snapshot. Source time: ${snapshotTime ? formatDate(snapshotTime, 'MMM d · HH:mm:ss') : 'not available'}. This is not an independent database, Kafka, Redis, or Snowflake health probe.` },
    { id: 'audit', title: 'Recorded changes', subtitle: 'Durable audit register', ready: auditReady, detail: 'A successful audit response verifies access to recorded changes in the current tenant. Missing entries are not evidence that no changes occurred; the register is a bounded recent sample.' },
  ]
  const active = checks.find(check => check.id === selected)!
  return <section className="civic-plate"><SectionHeader title="Verified service connections" description="Select a check to inspect what its response actually establishes" action={<button type="button" className="button button-secondary" onClick={onRefresh} disabled={checking}>{checking ? 'Checking…' : 'Refresh checks'}</button>} /><div className="assurance-console"><div className="assurance-topology"><div className="assurance-route">{checks.map(check => <button type="button" key={check.id} aria-pressed={selected === check.id} onClick={() => setSelected(check.id)}><strong>{check.title}</strong><small>{check.subtitle}</small><StatusBadge tone={check.ready ? 'success' : 'warning'}>{check.ready ? 'Response verified' : checking ? 'Checking' : 'Not verified'}</StatusBadge></button>)}</div><p>CLIENT SESSION → AUTHORIZED READ RESPONSES<br />Independent infrastructure probes: not performed. No secret configuration is exposed.</p></div><div className="assurance-detail" aria-live="polite"><h3>{active.title}</h3><p>{active.detail}</p><p className="civic-provenance">Selected check: {active.ready ? 'verified response' : 'not verified'} · refresh to recheck browser connectivity.</p></div></div></section>
}

export function AuditRegister({ events }: { events: AuditEvent[] }) {
  const [filter, setFilter] = useState('all')
  const [selectedId, setSelectedId] = useState('')
  const kinds = Array.from(new Set(events.map(event => event.entity_type))).sort()
  const rows = events.filter(event => filter === 'all' || event.entity_type === filter)
  const selected = rows.find(event => event.audit_id === selectedId) || rows[0]
  return <section className="civic-plate"><SectionHeader title="Recent change ledger" description="Recorded tenant events · select an entry for its actor and source record" action={<label className="inline-select"><span>Record type</span><select aria-label="Audit record type" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All records</option>{kinds.map(kind => <option key={kind}>{kind}</option>)}</select></label>} /><div className="civic-scroll audit-register" tabIndex={0} aria-label="Recent changes"><table className="civic-table"><thead><tr><th>Recorded time</th><th>Action / summary</th><th>Record</th><th>Actor</th></tr></thead><tbody>{rows.map(event => <tr key={event.audit_id} className={selected?.audit_id === event.audit_id ? 'is-selected' : undefined}><td>{formatDate(event.created_at, 'MMM d · HH:mm')}</td><th><button type="button" aria-pressed={selected?.audit_id === event.audit_id} onClick={() => setSelectedId(event.audit_id)}>{event.summary}<small>{event.action}</small></button></th><td>{event.entity_type}</td><td>{event.actor}</td></tr>)}</tbody></table>{!rows.length && <p className="civic-empty">No matching recorded events in this recent sample.</p>}</div>{selected && <div className="audit-detail" aria-live="polite"><strong>{selected.action}</strong> · {selected.entity_type} / {selected.entity_id}<br /><small>{selected.summary} · recorded by {selected.actor} at {formatDate(selected.created_at, 'MMM d, yyyy · HH:mm:ss')}</small></div>}</section>
}
