-- Aegis Command least-privilege Snowflake foundation.
-- Run with a role allowed to manage security and SYSADMIN-owned objects.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS AEGIS_PLATFORM_ADMIN
    COMMENT = 'Owns Aegis warehouse objects and tenant security policy';
CREATE ROLE IF NOT EXISTS AEGIS_LOADER
    COMMENT = 'Writes connector landing and normalized raw events';
CREATE ROLE IF NOT EXISTS AEGIS_TRANSFORMER
    COMMENT = 'Reads raw events and maintains analytical aggregates';
CREATE ROLE IF NOT EXISTS AEGIS_READER
    COMMENT = 'Reads policy-filtered command views';

GRANT ROLE AEGIS_LOADER TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT ROLE AEGIS_TRANSFORMER TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT ROLE AEGIS_READER TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT ROLE AEGIS_PLATFORM_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS AEGIS_INGEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Aegis event normalization and incremental analytics';

CREATE DATABASE IF NOT EXISTS AEGIS_ANALYTICS
    COMMENT = 'Tenant-scoped Aegis Command analytical plane';
CREATE SCHEMA IF NOT EXISTS AEGIS_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS AEGIS_ANALYTICS.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS AEGIS_ANALYTICS.SECURITY;

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE AEGIS_INGEST TO ROLE AEGIS_LOADER;
GRANT USAGE ON WAREHOUSE AEGIS_INGEST TO ROLE AEGIS_TRANSFORMER;
GRANT USAGE, OPERATE ON WAREHOUSE AEGIS_INGEST TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT USAGE ON DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT USAGE, CREATE SCHEMA ON DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK, CREATE ROW ACCESS POLICY
    ON ALL SCHEMAS IN DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE AEGIS_PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE AEGIS_INGEST TO ROLE AEGIS_READER;
GRANT USAGE ON DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_LOADER;
GRANT USAGE ON DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_TRANSFORMER;
GRANT USAGE ON DATABASE AEGIS_ANALYTICS TO ROLE AEGIS_READER;

GRANT USAGE ON SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_LOADER;

GRANT USAGE ON SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AEGIS_ANALYTICS.RAW TO ROLE AEGIS_TRANSFORMER;
GRANT USAGE ON SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_TRANSFORMER;

GRANT USAGE ON SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_READER;
GRANT USAGE ON SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_LOADER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_LOADER;
GRANT SELECT ON ALL VIEWS IN SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AEGIS_ANALYTICS.ANALYTICS TO ROLE AEGIS_READER;
