-- Tenant-scoped warehouse objects. PostgreSQL remains the source of truth.

USE ROLE AEGIS_PLATFORM_ADMIN;
USE WAREHOUSE AEGIS_INGEST;
USE DATABASE AEGIS_ANALYTICS;

CREATE TABLE IF NOT EXISTS SECURITY.ROLE_ORGANIZATION_ACCESS (
    ROLE_NAME VARCHAR(255) NOT NULL,
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    GRANTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    GRANTED_BY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
    CONSTRAINT ROLE_ORGANIZATION_ACCESS_PK PRIMARY KEY (ROLE_NAME, ORGANIZATION_ID)
)
COMMENT = 'Explicit reader-role to tenant mapping used by the row access policy';

CREATE OR ALTER ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY
AS (ROW_ORGANIZATION_ID VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'AEGIS_PLATFORM_ADMIN', 'AEGIS_LOADER', 'AEGIS_TRANSFORMER')
    OR EXISTS (
        SELECT 1
        FROM SECURITY.ROLE_ORGANIZATION_ACCESS ACCESS_MAP
        WHERE ACCESS_MAP.ROLE_NAME = CURRENT_ROLE()
          AND ACCESS_MAP.ORGANIZATION_ID = ROW_ORGANIZATION_ID
    );

CREATE TABLE IF NOT EXISTS RAW.OPERATIONAL_EVENTS (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    EVENT_ID VARCHAR(128) NOT NULL,
    EVENT_TYPE VARCHAR(160) NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL,
    TOPIC_CLASS VARCHAR(20) NOT NULL,
    SOURCE VARCHAR(120) NOT NULL,
    SCHEMA_VERSION NUMBER(9, 0) NOT NULL,
    AGGREGATE_TYPE VARCHAR(80) NOT NULL,
    AGGREGATE_ID VARCHAR(128) NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    PAYLOAD VARIANT NOT NULL,
    KAFKA_TOPIC VARCHAR(255),
    KAFKA_PARTITION NUMBER(9, 0),
    KAFKA_OFFSET NUMBER(38, 0),
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT OPERATIONAL_EVENTS_PK PRIMARY KEY (ORGANIZATION_ID, EVENT_ID)
)
CLUSTER BY (ORGANIZATION_ID, TO_DATE(OCCURRED_AT), EVENT_TYPE)
COMMENT = 'Versioned, tenant-scoped events normalized from Kafka';

CREATE TABLE IF NOT EXISTS RAW.STATIONS (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    STATION_ID VARCHAR(64) NOT NULL,
    STATION_NUMBER VARCHAR(20),
    NAME VARCHAR(180) NOT NULL,
    BATTALION_ID VARCHAR(64),
    ADDRESS VARCHAR(240),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT STATIONS_PK PRIMARY KEY (ORGANIZATION_ID, STATION_ID)
);

CREATE TABLE IF NOT EXISTS RAW.UNITS (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    UNIT_ID VARCHAR(64) NOT NULL,
    STATION_ID VARCHAR(64),
    CALL_SIGN VARCHAR(80) NOT NULL,
    UNIT_TYPE VARCHAR(50) NOT NULL,
    MINIMUM_STAFF NUMBER(9, 0) NOT NULL,
    REQUIRED_CERTIFICATIONS ARRAY NOT NULL,
    OPERATIONAL_STATUS VARCHAR(40) NOT NULL DEFAULT 'AVAILABLE',
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UNITS_PK PRIMARY KEY (ORGANIZATION_ID, UNIT_ID)
);

CREATE TABLE IF NOT EXISTS RAW.PERSONNEL (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    PERSONNEL_ID VARCHAR(64) NOT NULL,
    STATION_ID VARCHAR(64),
    CURRENT_UNIT_ID VARCHAR(64),
    NAME VARCHAR(180) NOT NULL,
    RANK VARCHAR(80),
    ROLE VARCHAR(120) NOT NULL,
    AVAILABILITY_STATUS VARCHAR(40) NOT NULL,
    LAST_CHECK_IN TIMESTAMP_TZ,
    CERTIFICATIONS ARRAY NOT NULL,
    CERT_EXPIRATIONS OBJECT NOT NULL,
    NOTES VARCHAR,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PERSONNEL_PK PRIMARY KEY (ORGANIZATION_ID, PERSONNEL_ID)
);

CREATE TABLE IF NOT EXISTS RAW.UNIT_ASSIGNMENTS (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    ASSIGNMENT_ID VARCHAR(64) NOT NULL,
    UNIT_ID VARCHAR(64) NOT NULL,
    PERSONNEL_ID VARCHAR(64) NOT NULL,
    SHIFT_START TIMESTAMP_TZ NOT NULL,
    SHIFT_END TIMESTAMP_TZ NOT NULL,
    ASSIGNMENT_STATUS VARCHAR(40) NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UNIT_ASSIGNMENTS_PK PRIMARY KEY (ORGANIZATION_ID, ASSIGNMENT_ID)
);

CREATE TABLE IF NOT EXISTS ANALYTICS.UNIT_READINESS_HOURLY (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    HOUR_START TIMESTAMP_TZ NOT NULL,
    UNIT_ID VARCHAR(64) NOT NULL,
    STATION_ID VARCHAR(64),
    UNIT_TYPE VARCHAR(50),
    MINIMUM_STAFF NUMBER(9, 0),
    STAFF_PRESENT NUMBER(9, 0),
    READINESS_SCORE NUMBER(5, 2),
    UNDERSTAFFED_FLAG BOOLEAN,
    MISSING_CERTIFICATIONS ARRAY,
    SOURCE_EVENT_ID VARCHAR(128) NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UNIT_READINESS_HOURLY_PK PRIMARY KEY (ORGANIZATION_ID, HOUR_START, UNIT_ID)
)
CLUSTER BY (ORGANIZATION_ID, TO_DATE(HOUR_START));

CREATE TABLE IF NOT EXISTS ANALYTICS.INCIDENT_ACTIVITY_HOURLY (
    ORGANIZATION_ID VARCHAR(64) NOT NULL,
    HOUR_START TIMESTAMP_TZ NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL,
    EVENTS NUMBER(38, 0) NOT NULL,
    DISTINCT_INCIDENTS NUMBER(38, 0) NOT NULL,
    FIRST_EVENT_AT TIMESTAMP_TZ,
    LAST_EVENT_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT INCIDENT_ACTIVITY_HOURLY_PK PRIMARY KEY (ORGANIZATION_ID, HOUR_START, PRIORITY)
)
CLUSTER BY (ORGANIZATION_ID, TO_DATE(HOUR_START));

ALTER TABLE RAW.OPERATIONAL_EVENTS
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE RAW.STATIONS
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE RAW.UNITS
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE RAW.PERSONNEL
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE RAW.UNIT_ASSIGNMENTS
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE ANALYTICS.UNIT_READINESS_HOURLY
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
ALTER TABLE ANALYTICS.INCIDENT_ACTIVITY_HOURLY
    ADD ROW ACCESS POLICY SECURITY.TENANT_ACCESS_POLICY ON (ORGANIZATION_ID);
