-- Snowflake Kafka Connector landing contract and deterministic normalization.

USE ROLE AEGIS_PLATFORM_ADMIN;
USE WAREHOUSE AEGIS_INGEST;
USE DATABASE AEGIS_ANALYTICS;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS KAFKA_EVENTS_LANDING (
    RECORD_METADATA VARIANT NOT NULL,
    RECORD_CONTENT VARIANT NOT NULL,
    LANDED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Standard Snowflake Kafka Connector landing shape';

CREATE TABLE IF NOT EXISTS EVENT_QUARANTINE (
    QUARANTINE_ID VARCHAR(64) NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT,
    QUARANTINED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT EVENT_QUARANTINE_PK PRIMARY KEY (QUARANTINE_ID)
)
COMMENT = 'Invalid connector records retained for diagnosis and replay';

CREATE STREAM IF NOT EXISTS KAFKA_EVENTS_LANDING_STREAM
    ON TABLE KAFKA_EVENTS_LANDING
    APPEND_ONLY = TRUE;

CREATE TASK IF NOT EXISTS NORMALIZE_KAFKA_EVENTS
    WAREHOUSE = AEGIS_INGEST
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('AEGIS_ANALYTICS.RAW.KAFKA_EVENTS_LANDING_STREAM')
AS
INSERT ALL
    WHEN ORGANIZATION_ID IS NOT NULL
     AND EVENT_TYPE IS NOT NULL
     AND AGGREGATE_TYPE IS NOT NULL
     AND AGGREGATE_ID IS NOT NULL
     AND OCCURRED_AT IS NOT NULL
    THEN INTO OPERATIONAL_EVENTS (
        ORGANIZATION_ID, EVENT_ID, EVENT_TYPE, PRIORITY, TOPIC_CLASS, SOURCE,
        SCHEMA_VERSION, AGGREGATE_TYPE, AGGREGATE_ID, OCCURRED_AT, PAYLOAD,
        KAFKA_TOPIC, KAFKA_PARTITION, KAFKA_OFFSET, INGESTED_AT
    ) VALUES (
        ORGANIZATION_ID, EVENT_ID, EVENT_TYPE, PRIORITY, TOPIC_CLASS, SOURCE,
        SCHEMA_VERSION, AGGREGATE_TYPE, AGGREGATE_ID, OCCURRED_AT, PAYLOAD,
        KAFKA_TOPIC, KAFKA_PARTITION, KAFKA_OFFSET, NORMALIZED_AT
    )
    ELSE INTO EVENT_QUARANTINE (
        QUARANTINE_ID, REASON, RECORD_METADATA, RECORD_CONTENT
    ) VALUES (
        QUARANTINE_ID,
        REJECTION_REASON,
        RECORD_METADATA, RECORD_CONTENT
    )
SELECT
    RECORD_CONTENT:organization_id::VARCHAR AS ORGANIZATION_ID,
    COALESCE(
        RECORD_CONTENT:event_id::VARCHAR,
        SHA2(CONCAT_WS(':', RECORD_METADATA:topic::VARCHAR,
            RECORD_METADATA:partition::VARCHAR, RECORD_METADATA:offset::VARCHAR), 256)
    ) AS EVENT_ID,
    RECORD_CONTENT:event_type::VARCHAR AS EVENT_TYPE,
    COALESCE(RECORD_CONTENT:priority::VARCHAR, 'NORMAL') AS PRIORITY,
    COALESCE(RECORD_CONTENT:topic_class::VARCHAR, 'bulk') AS TOPIC_CLASS,
    COALESCE(RECORD_CONTENT:source::VARCHAR, 'kafka') AS SOURCE,
    COALESCE(TRY_TO_NUMBER(RECORD_CONTENT:schema_version::VARCHAR), 1) AS SCHEMA_VERSION,
    RECORD_CONTENT:aggregate_type::VARCHAR AS AGGREGATE_TYPE,
    RECORD_CONTENT:aggregate_id::VARCHAR AS AGGREGATE_ID,
    TRY_TO_TIMESTAMP_TZ(RECORD_CONTENT:occurred_at::VARCHAR) AS OCCURRED_AT,
    COALESCE(RECORD_CONTENT:payload, OBJECT_CONSTRUCT()) AS PAYLOAD,
    RECORD_METADATA:topic::VARCHAR AS KAFKA_TOPIC,
    TRY_TO_NUMBER(RECORD_METADATA:partition::VARCHAR) AS KAFKA_PARTITION,
    TRY_TO_NUMBER(RECORD_METADATA:offset::VARCHAR) AS KAFKA_OFFSET,
    CURRENT_TIMESTAMP() AS NORMALIZED_AT,
    SHA2(TO_JSON(RECORD_METADATA) || TO_JSON(RECORD_CONTENT), 256) AS QUARANTINE_ID,
    'Required tenant, event, aggregate, or timestamp field is missing' AS REJECTION_REASON,
    RECORD_METADATA,
    RECORD_CONTENT
FROM KAFKA_EVENTS_LANDING_STREAM
WHERE METADATA$ACTION = 'INSERT';

ALTER TASK NORMALIZE_KAFKA_EVENTS RESUME;
