-- Independent event streams prevent one analytical consumer from starving another.

USE ROLE AEGIS_PLATFORM_ADMIN;
USE WAREHOUSE AEGIS_INGEST;
USE DATABASE AEGIS_ANALYTICS;

CREATE STREAM IF NOT EXISTS RAW.UNIT_READINESS_EVENT_STREAM
    ON TABLE RAW.OPERATIONAL_EVENTS
    APPEND_ONLY = TRUE;
CREATE STREAM IF NOT EXISTS RAW.INCIDENT_ACTIVITY_EVENT_STREAM
    ON TABLE RAW.OPERATIONAL_EVENTS
    APPEND_ONLY = TRUE;

CREATE TASK IF NOT EXISTS ANALYTICS.PROCESS_UNIT_READINESS
    WAREHOUSE = AEGIS_INGEST
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('AEGIS_ANALYTICS.RAW.UNIT_READINESS_EVENT_STREAM')
AS
MERGE INTO ANALYTICS.UNIT_READINESS_HOURLY TARGET
USING (
    SELECT
        ORGANIZATION_ID,
        DATE_TRUNC('HOUR', OCCURRED_AT) AS HOUR_START,
        AGGREGATE_ID AS UNIT_ID,
        PAYLOAD:station_id::VARCHAR AS STATION_ID,
        PAYLOAD:unit_type::VARCHAR AS UNIT_TYPE,
        PAYLOAD:minimum_staff::NUMBER AS MINIMUM_STAFF,
        PAYLOAD:staff_present::NUMBER AS STAFF_PRESENT,
        PAYLOAD:readiness_score::NUMBER(5, 2) AS READINESS_SCORE,
        PAYLOAD:understaffed::BOOLEAN AS UNDERSTAFFED_FLAG,
        COALESCE(PAYLOAD:missing_certifications::ARRAY, ARRAY_CONSTRUCT()) AS MISSING_CERTIFICATIONS,
        EVENT_ID AS SOURCE_EVENT_ID
    FROM RAW.UNIT_READINESS_EVENT_STREAM
    WHERE METADATA$ACTION = 'INSERT'
      AND EVENT_TYPE IN ('unit.readiness.updated', 'unit.readiness.alerted')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORGANIZATION_ID, DATE_TRUNC('HOUR', OCCURRED_AT), AGGREGATE_ID
        ORDER BY OCCURRED_AT DESC, INGESTED_AT DESC
    ) = 1
) SOURCE
ON TARGET.ORGANIZATION_ID = SOURCE.ORGANIZATION_ID
AND TARGET.HOUR_START = SOURCE.HOUR_START
AND TARGET.UNIT_ID = SOURCE.UNIT_ID
WHEN MATCHED THEN UPDATE SET
    STATION_ID = SOURCE.STATION_ID,
    UNIT_TYPE = SOURCE.UNIT_TYPE,
    MINIMUM_STAFF = SOURCE.MINIMUM_STAFF,
    STAFF_PRESENT = SOURCE.STAFF_PRESENT,
    READINESS_SCORE = SOURCE.READINESS_SCORE,
    UNDERSTAFFED_FLAG = SOURCE.UNDERSTAFFED_FLAG,
    MISSING_CERTIFICATIONS = SOURCE.MISSING_CERTIFICATIONS,
    SOURCE_EVENT_ID = SOURCE.SOURCE_EVENT_ID,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    ORGANIZATION_ID, HOUR_START, UNIT_ID, STATION_ID, UNIT_TYPE,
    MINIMUM_STAFF, STAFF_PRESENT, READINESS_SCORE, UNDERSTAFFED_FLAG,
    MISSING_CERTIFICATIONS, SOURCE_EVENT_ID
) VALUES (
    SOURCE.ORGANIZATION_ID, SOURCE.HOUR_START, SOURCE.UNIT_ID, SOURCE.STATION_ID, SOURCE.UNIT_TYPE,
    SOURCE.MINIMUM_STAFF, SOURCE.STAFF_PRESENT, SOURCE.READINESS_SCORE, SOURCE.UNDERSTAFFED_FLAG,
    SOURCE.MISSING_CERTIFICATIONS, SOURCE.SOURCE_EVENT_ID
);

CREATE TASK IF NOT EXISTS ANALYTICS.PROCESS_INCIDENT_ACTIVITY
    WAREHOUSE = AEGIS_INGEST
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('AEGIS_ANALYTICS.RAW.INCIDENT_ACTIVITY_EVENT_STREAM')
AS
MERGE INTO ANALYTICS.INCIDENT_ACTIVITY_HOURLY TARGET
USING (
    WITH CHANGED_HOURS AS (
        SELECT DISTINCT ORGANIZATION_ID, DATE_TRUNC('HOUR', OCCURRED_AT) AS HOUR_START, PRIORITY
        FROM RAW.INCIDENT_ACTIVITY_EVENT_STREAM
        WHERE METADATA$ACTION = 'INSERT' AND AGGREGATE_TYPE = 'incident'
    ), DEDUPLICATED AS (
        SELECT E.*
        FROM RAW.OPERATIONAL_EVENTS E
        JOIN CHANGED_HOURS H ON E.ORGANIZATION_ID = H.ORGANIZATION_ID
            AND DATE_TRUNC('HOUR', E.OCCURRED_AT) = H.HOUR_START AND E.PRIORITY = H.PRIORITY
        WHERE E.AGGREGATE_TYPE = 'incident'
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY E.ORGANIZATION_ID, E.EVENT_ID ORDER BY E.INGESTED_AT DESC
        ) = 1
    )
    SELECT
        ORGANIZATION_ID,
        DATE_TRUNC('HOUR', OCCURRED_AT) AS HOUR_START,
        PRIORITY,
        COUNT(*) AS EVENTS,
        COUNT(DISTINCT AGGREGATE_ID) AS DISTINCT_INCIDENTS,
        MIN(OCCURRED_AT) AS FIRST_EVENT_AT,
        MAX(OCCURRED_AT) AS LAST_EVENT_AT
    FROM DEDUPLICATED
    GROUP BY ORGANIZATION_ID, DATE_TRUNC('HOUR', OCCURRED_AT), PRIORITY
) SOURCE
ON TARGET.ORGANIZATION_ID = SOURCE.ORGANIZATION_ID
AND TARGET.HOUR_START = SOURCE.HOUR_START
AND TARGET.PRIORITY = SOURCE.PRIORITY
WHEN MATCHED THEN UPDATE SET
    EVENTS = SOURCE.EVENTS,
    DISTINCT_INCIDENTS = SOURCE.DISTINCT_INCIDENTS,
    FIRST_EVENT_AT = LEAST(TARGET.FIRST_EVENT_AT, SOURCE.FIRST_EVENT_AT),
    LAST_EVENT_AT = GREATEST(TARGET.LAST_EVENT_AT, SOURCE.LAST_EVENT_AT),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    ORGANIZATION_ID, HOUR_START, PRIORITY, EVENTS, DISTINCT_INCIDENTS,
    FIRST_EVENT_AT, LAST_EVENT_AT
) VALUES (
    SOURCE.ORGANIZATION_ID, SOURCE.HOUR_START, SOURCE.PRIORITY, SOURCE.EVENTS,
    SOURCE.DISTINCT_INCIDENTS, SOURCE.FIRST_EVENT_AT, SOURCE.LAST_EVENT_AT
);

ALTER TASK ANALYTICS.PROCESS_UNIT_READINESS RESUME;
ALTER TASK ANALYTICS.PROCESS_INCIDENT_ACTIVITY RESUME;
