-- Policy-filtered command views. Secure views prevent definition leakage to readers.

USE ROLE AEGIS_PLATFORM_ADMIN;
USE WAREHOUSE AEGIS_INGEST;
USE DATABASE AEGIS_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE SECURE VIEW CURRENT_UNIT_READINESS AS
SELECT
    ORGANIZATION_ID,
    UNIT_ID,
    STATION_ID,
    UNIT_TYPE,
    MINIMUM_STAFF,
    STAFF_PRESENT,
    READINESS_SCORE,
    UNDERSTAFFED_FLAG,
    MISSING_CERTIFICATIONS,
    HOUR_START,
    CASE
        WHEN READINESS_SCORE >= 85 THEN 'READY'
        WHEN READINESS_SCORE >= 60 THEN 'DEGRADED'
        ELSE 'CRITICAL'
    END AS READINESS_BAND
FROM UNIT_READINESS_HOURLY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ORGANIZATION_ID, UNIT_ID
    ORDER BY HOUR_START DESC, UPDATED_AT DESC
) = 1;

CREATE OR REPLACE SECURE VIEW STATION_READINESS_CURRENT AS
SELECT
    ORGANIZATION_ID,
    STATION_ID,
    COUNT(*) AS TOTAL_UNITS,
    COUNT_IF(READINESS_BAND = 'READY') AS READY_UNITS,
    COUNT_IF(READINESS_BAND = 'DEGRADED') AS DEGRADED_UNITS,
    COUNT_IF(READINESS_BAND = 'CRITICAL') AS CRITICAL_UNITS,
    AVG(READINESS_SCORE) AS AVERAGE_READINESS,
    SUM(GREATEST(MINIMUM_STAFF - STAFF_PRESENT, 0)) AS OPEN_STAFFING_POSITIONS,
    MAX(HOUR_START) AS AS_OF
FROM CURRENT_UNIT_READINESS
GROUP BY ORGANIZATION_ID, STATION_ID;

CREATE OR REPLACE SECURE VIEW INCIDENT_TEMPO_24H AS
SELECT
    ORGANIZATION_ID,
    HOUR_START,
    PRIORITY,
    EVENTS,
    DISTINCT_INCIDENTS,
    FIRST_EVENT_AT,
    LAST_EVENT_AT
FROM INCIDENT_ACTIVITY_HOURLY
WHERE HOUR_START >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP());

CREATE OR REPLACE SECURE VIEW TENANT_PIPELINE_HEALTH AS
SELECT
    ORGANIZATION_ID,
    COUNT(*) AS EVENTS_24H,
    COUNT_IF(TOPIC_CLASS = 'alert') AS ALERT_EVENTS_24H,
    COUNT_IF(TOPIC_CLASS = 'bulk') AS BULK_EVENTS_24H,
    MAX(OCCURRED_AT) AS LATEST_EVENT_AT,
    MAX(INGESTED_AT) AS LATEST_INGEST_AT,
    DATEDIFF('SECOND', MAX(OCCURRED_AT), MAX(INGESTED_AT)) AS LATEST_INGEST_DELAY_SECONDS
FROM RAW.OPERATIONAL_EVENTS
WHERE INGESTED_AT >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
GROUP BY ORGANIZATION_ID;

GRANT SELECT ON VIEW CURRENT_UNIT_READINESS TO ROLE AEGIS_READER;
GRANT SELECT ON VIEW STATION_READINESS_CURRENT TO ROLE AEGIS_READER;
GRANT SELECT ON VIEW INCIDENT_TEMPO_24H TO ROLE AEGIS_READER;
GRANT SELECT ON VIEW TENANT_PIPELINE_HEALTH TO ROLE AEGIS_READER;
