-- Evidence-oriented deployment and data-quality checks.

USE ROLE AEGIS_PLATFORM_ADMIN;
USE WAREHOUSE AEGIS_INGEST;
USE DATABASE AEGIS_ANALYTICS;

SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW', 'ANALYTICS', 'SECURITY')
ORDER BY TABLE_SCHEMA, TABLE_NAME;

SELECT
    COUNT_IF(ORGANIZATION_ID IS NULL) AS MISSING_TENANT,
    COUNT_IF(EVENT_ID IS NULL) AS MISSING_EVENT_ID,
    COUNT_IF(OCCURRED_AT IS NULL) AS MISSING_OCCURRED_AT,
    COUNT(*) - COUNT(DISTINCT ORGANIZATION_ID || ':' || EVENT_ID) AS DUPLICATE_TENANT_EVENT_KEYS
FROM RAW.OPERATIONAL_EVENTS;

SELECT REASON, COUNT(*) AS QUARANTINED_RECORDS, MAX(QUARANTINED_AT) AS LATEST
FROM RAW.EVENT_QUARANTINE
GROUP BY REASON
ORDER BY QUARANTINED_RECORDS DESC;

SHOW TASKS IN DATABASE AEGIS_ANALYTICS;

SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_CODE, ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(SCHEDULED_TIME_RANGE_START => DATEADD('HOUR', -24, CURRENT_TIMESTAMP())))
WHERE DATABASE_NAME = 'AEGIS_ANALYTICS'
ORDER BY SCHEDULED_TIME DESC;

SELECT * FROM ANALYTICS.TENANT_PIPELINE_HEALTH ORDER BY ORGANIZATION_ID;
